config/routes.rb
TravelingProfessional::Application.routes.draw do
  get "home/index"

  resources :users

  resources :trips

   root :to => 'home#index'

end

app/models/trip.rb
class Trip < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, :notice => 'Trip was successfully created.' }
        format.json { render :json => @trip, :status => :created, :location => @trip }
      else
        format.html { render :action => "new" }
        format.json { render :json => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, :notice => 'Trip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @trip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Welcome to Traveling Professional</h1>
<p><%= link_to "Trip Information", trips_path %></p>
<p><%= link_to "Users", users_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelingProfessional</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Date %><br />
    <%= f.date_select :Date %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.time_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :distance_from_home %><br />
    <%= f.number_field :distance_from_home %>
  </div>
  <div class="field">
    <%= f.label :travel_time %><br />
    <%= f.number_field :travel_time %>
  </div>
  <div class="field">
    <%= f.label :departure_time %><br />
    <%= f.time_select :departure_time %>
  </div>
  <div class="field">
    <%= f.label :distance_from_school_to_office %><br />
    <%= f.number_field :distance_from_school_to_office %>
  </div>
  <div class="field">
    <%= f.label :time_from_school_to_office %><br />
    <%= f.number_field :time_from_school_to_office %>
  </div>
  <div class="field">
    <%= f.label :distance_from_home_to_office %><br />
    <%= f.number_field :distance_from_home_to_office %>
  </div>
  <div class="field">
    <%= f.label :time_to_home %><br />
    <%= f.number_field :time_to_home %>
  </div>
  <div class="field">
    <%= f.label :current_gas_price %><br />
    <%= f.text_field :current_gas_price %>
  </div>
  <div class="field">
    <%= f.label :trip_gas_total %><br />
    <%= f.text_field :trip_gas_total %>
  </div>
  <div class="field">
    <%= f.label :end_of_business %><br />
    <%= f.time_select :end_of_business %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :total_business_time %><br />
    <%= f.number_field :total_business_time %>
  </div>
  <div class="field">
    <%= f.label :hourly_rate %><br />
    <%= f.text_field :hourly_rate %>
  </div>
  <div class="field">
    <%= f.label :business_time %><br />
    <%= f.number_field :business_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Address</th>
    <th>School</th>
    <th>Start time</th>
    <th>Distance from home</th>
    <th>Travel time</th>
    <th>Departure time</th>
    <th>Distance from school to office</th>
    <th>Time from school to office</th>
    <th>Distance from home to office</th>
    <th>Time to home</th>
    <th>Current gas price</th>
    <th>Trip gas total</th>
    <th>End of business</th>
    <th>Position</th>
    <th>Total business time</th>
    <th>Hourly rate</th>
    <th>Business time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.Date %></td>
    <td><%= trip.address %></td>
    <td><%= trip.school %></td>
    <td><%= trip.start_time %></td>
    <td><%= trip.distance_from_home %></td>
    <td><%= trip.travel_time %></td>
    <td><%= trip.departure_time %></td>
    <td><%= trip.distance_from_school_to_office %></td>
    <td><%= trip.time_from_school_to_office %></td>
    <td><%= trip.distance_from_home_to_office %></td>
    <td><%= trip.time_to_home %></td>
    <td><%= trip.current_gas_price %></td>
    <td><%= trip.trip_gas_total %></td>
    <td><%= trip.end_of_business %></td>
    <td><%= trip.position %></td>
    <td><%= trip.total_business_time %></td>
    <td><%= trip.hourly_rate %></td>
    <td><%= trip.business_time %></td>
    <td><%= link_to 'Show', trip %></td>
    <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
    <td><%= link_to 'Destroy', trip, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @trip.Date %>
</p>

<p>
  <b>Address:</b>
  <%= @trip.address %>
</p>

<p>
  <b>School:</b>
  <%= @trip.school %>
</p>

<p>
  <b>Start time:</b>
  <%= @trip.start_time %>
</p>

<p>
  <b>Distance from home:</b>
  <%= @trip.distance_from_home %>
</p>

<p>
  <b>Travel time:</b>
  <%= @trip.travel_time %>
</p>

<p>
  <b>Departure time:</b>
  <%= @trip.departure_time %>
</p>

<p>
  <b>Distance from school to office:</b>
  <%= @trip.distance_from_school_to_office %>
</p>

<p>
  <b>Time from school to office:</b>
  <%= @trip.time_from_school_to_office %>
</p>

<p>
  <b>Distance from home to office:</b>
  <%= @trip.distance_from_home_to_office %>
</p>

<p>
  <b>Time to home:</b>
  <%= @trip.time_to_home %>
</p>

<p>
  <b>Current gas price:</b>
  <%= @trip.current_gas_price %>
</p>

<p>
  <b>Trip gas total:</b>
  <%= @trip.trip_gas_total %>
</p>

<p>
  <b>End of business:</b>
  <%= @trip.end_of_business %>
</p>

<p>
  <b>Position:</b>
  <%= @trip.position %>
</p>

<p>
  <b>Total business time:</b>
  <%= @trip.total_business_time %>
</p>

<p>
  <b>Hourly rate:</b>
  <%= @trip.hourly_rate %>
</p>

<p>
  <b>Business time:</b>
  <%= @trip.business_time %>
</p>


<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>User</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.user %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user.user %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>